/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpoly.tn.gd;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author TRINH THE NAM
 */
public class frm_LognIn extends javax.swing.JFrame {

    /**
     * Creates new form frm_LognIn
     */
    public frm_LognIn() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        txt_Closing = new javax.swing.JLabel();
        txt_Closing1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_login = new javax.swing.JPanel();
        pw_pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btn_signin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_singin = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        txt_Closing.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_Closing.setForeground(new java.awt.Color(255, 255, 255));
        txt_Closing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Closing.setText("X");
        txt_Closing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ClosingMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(540, 610));
        setMinimumSize(new java.awt.Dimension(540, 610));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(540, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Closing1.setFont(new java.awt.Font("VNI-Lithos", 0, 24)); // NOI18N
        txt_Closing1.setForeground(new java.awt.Color(255, 255, 255));
        txt_Closing1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Closing1.setText("X");
        txt_Closing1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_Closing1MouseClicked(evt);
            }
        });
        getContentPane().add(txt_Closing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -1, 80, 60));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TRINH THE NAM\\Documents\\Java_3_Cuong\\ASM_Java_3_Namttpk01498\\src\\fpoly\\tn\\images\\icons8_cloud_account_login_male_100px.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        pnl_login.setBackground(new java.awt.Color(255, 255, 255));
        pnl_login.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(85, 14, 50)));
        pnl_login.setMaximumSize(new java.awt.Dimension(540, 610));
        pnl_login.setMinimumSize(new java.awt.Dimension(540, 610));
        pnl_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pw_pass.setBorder(null);
        pnl_login.add(pw_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 210, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Password");
        pnl_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("User Name");
        jLabel3.setPreferredSize(new java.awt.Dimension(48, 20));
        pnl_login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 60, 40));

        txt_username.setBorder(null);
        pnl_login.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 210, 20));
        pnl_login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 210, 10));
        pnl_login.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 210, 10));
        pnl_login.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 210, 10));

        btn_signin.setBackground(new java.awt.Color(255, 255, 255));
        btn_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_signinMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("UTM Cookies", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\TRINH THE NAM\\Documents\\Java_3_Cuong\\ASM_Java_3_Namttpk01498\\src\\fpoly\\tn\\images\\btn.png")); // NOI18N
        jLabel4.setText("Sign In");

        lbl_singin.setFont(new java.awt.Font("UTM Kabel KT", 0, 18)); // NOI18N
        lbl_singin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_singin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_singin.setText("Sign In");

        javax.swing.GroupLayout btn_signinLayout = new javax.swing.GroupLayout(btn_signin);
        btn_signin.setLayout(btn_signinLayout);
        btn_signinLayout.setHorizontalGroup(
            btn_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_signinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_singin, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(btn_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_signinLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btn_signinLayout.setVerticalGroup(
            btn_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_signinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_singin, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_signinLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnl_login.add(btn_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 220, 70));

        lbl_background.setIcon(new javax.swing.ImageIcon("C:\\Users\\TRINH THE NAM\\Documents\\Java_3_Cuong\\ASM_Java_3_Namttpk01498\\src\\fpoly\\tn\\images\\Background.png")); // NOI18N
        pnl_login.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 550, 280));

        getContentPane().add(pnl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 610));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ClosingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ClosingMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txt_ClosingMouseClicked

    private void txt_Closing1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_Closing1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_txt_Closing1MouseClicked

    private void btn_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseClicked
        // TODO add your handling code here:
        frm_QuanLy frmQL = new frm_QuanLy();
        frmQL.setVisible(true);
        frm_LognIn frmLog = new frm_LognIn();
        frmLog.setVisible(false);

    }//GEN-LAST:event_btn_signinMouseClicked

    private void btn_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_signinMouseEntered

    private void btn_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_signinMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_LognIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_LognIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_LognIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_LognIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_LognIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_signin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_singin;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPasswordField pw_pass;
    private javax.swing.JLabel txt_Closing;
    private javax.swing.JLabel txt_Closing1;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
